- id: ftp-001
  name: "Anonymous login is enabled"
  match: "anonymous_enable=YES"
  description: "Allows anyone to log in without authentication, which poses a significant security risk."
  severity: "high"

- id: ftp-002
  name: "Local user write access is enabled"
  match: "write_enable=YES"
  description: "Allows authenticated local users to upload and modify files. Should be disabled unless necessary."
  severity: "medium"

- id: ftp-003
  name: "Chroot for local users is disabled"
  match: "chroot_local_user=NO"
  description: "Disabling chroot allows users to navigate outside their home directory, potentially accessing sensitive files."
  severity: "high"

- id: ftp-004
  name: "FTP server is not using TLS"
  match: "ssl_enable=NO"
  description: "Data and credentials are transmitted in plain text, making them vulnerable to sniffing attacks."
  severity: "critical"

- id: ftp-005
  name: "Passive mode ports are not restricted"
  match: "pasv_min_port="
  description: "Failing to set a restricted passive port range can cause firewall issues and unnecessary exposure."
  severity: "medium"

- id: ftp-006
  name: "Banner not configured"
  match: "ftpd_banner="
  description: "Missing login banner may indicate a default configuration and doesn't warn users about access policies."
  severity: "low"

- id: ftp-007
  name: "Max clients not limited"
  match: "max_clients=0"
  description: "Unlimited clients can allow DoS attacks or overload the server. Always limit concurrent sessions."
  severity: "medium"

- id: ftp-008
  name: "Max per IP not limited"
  match: "max_per_ip=0"
  description: "Unlimited connections per IP can allow abuse or scanning. Always enforce limits."
  severity: "medium"

- id: ftp-009
  name: "Logging is disabled"
  match: "xferlog_enable=NO"
  description: "Disabling logs makes it difficult to track activity or investigate incidents."
  severity: "high"

- id: ftp-010
  name: "Default umask is too permissive"
  match: "local_umask=000"
  description: "Files uploaded by users may be world-readable/writable if the umask is insecure."
  severity: "high"
