- id: redis-001
  name: "Binding to all interfaces"
  match: "bind 0.0.0.0"
  description: "Redis is open to the internet. It should only listen locally or on private networks."
  severity: "critical"

- id: redis-002
  name: "No authentication required"
  match: "^#?\\s*requirepass\\s*$"
  description: "Without a password, anyone can connect to and control Redis."
  severity: "critical"

- id: redis-003
  name: "Protected mode disabled"
  match: "protected-mode no"
  description: "Disabling protected mode exposes Redis to remote attackers if no auth is set."
  severity: "high"

- id: redis-004
  name: "Default port in use"
  match: "port 6379"
  description: "Default ports are easily scanned. Consider using a non-standard port."
  severity: "low"

- id: redis-005
  name: "Append only mode disabled"
  match: "appendonly no"
  description: "Disabling AOF increases the risk of data loss during unexpected shutdowns."
  severity: "medium"
