- id: ssh-001
  name: "Root login is enabled"
  match: "PermitRootLogin yes"
  description: "Allows direct root access, which increases risk of brute-force or privilege escalation attacks."
  severity: "critical"

- id: ssh-002
  name: "Password authentication is enabled"
  match: "PasswordAuthentication yes"
  description: "Allows login using passwords instead of keys. Susceptible to brute-force attacks."
  severity: "high"

- id: ssh-003
  name: "SSH protocol version 1 is allowed"
  match: "Protocol 1"
  description: "Protocol version 1 is outdated and insecure. Use version 2."
  severity: "high"

- id: ssh-004
  name: "Empty passwords are allowed"
  match: "PermitEmptyPasswords yes"
  description: "Users can log in without a password, which is a major security vulnerability."
  severity: "critical"

- id: ssh-005
  name: "MaxAuthTries is too high"
  match: "MaxAuthTries [5-9]|[1-9][0-9]+"
  description: "Too many authentication attempts allowed. Facilitates brute-force attacks."
  severity: "medium"

- id: ssh-006
  name: "X11 forwarding is enabled"
  match: "X11Forwarding yes"
  description: "X11 forwarding can be used to launch GUI apps over SSH, which may be exploited."
  severity: "low"

- id: ssh-007
  name: "Client alive interval not set"
  match: "^ClientAliveInterval\\s*0$"
  description: "Lack of session timeout can lead to idle open sessions, increasing risk."
  severity: "medium"
